version: '3.8'

services:
  front:
    build:
      context: ./front/.docker/local
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
      - db
    volumes:
      - ./front:/app
    networks:
      - app-network

  api:
    build:
      context: ./api/.docker/local
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db
    volumes:
      - ./api:/app
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
