version: '3.8'

services:
  # Serviço Frontend (Next.js)
  front:
    build:
      context: ./front
      target: development
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next
      - /app/.pnpm-store
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true  # Habilita polling para hot reload
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - app-network

  # Serviço API (Laravel)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    volumes:
      - ./api:/var/www
      - api_vendor:/var/www/vendor
    networks:
      - app-network
    depends_on:
      - db

  # Servidor Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www
      - ./api/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - api

  # Banco de Dados MySQL
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  front_node_modules:
  front_next:
  api_vendor:
