'use client'

import { ThemeProvider } from '../contexts/ThemeContext';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '@/contexts/AuthContext';
import { SettingsProvider } from '@/contexts/SettingsContext';
import { ThemeWrapper } from '@/components/ThemeWrapper';
import { CompanyThemeLoader } from '@/components/CompanyThemeLoader';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SettingsProvider>
          <CompanyThemeLoader>
            <AuthProvider>
              <ThemeProvider>
                <ThemeWrapper>
                  {children}
                </ThemeWrapper>
              </ThemeProvider>
            </AuthProvider>
          </CompanyThemeLoader>
        </SettingsProvider>
      </body>
    </html>
  );
}
